# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMAPqaJX_os-Urqph_q3QNW-JbsZuoeg
"""

from flask import Flask, request, jsonify, send_file
from werkzeug.utils import secure_filename
import os
from model_loader import load_model, predict_aadhar
from ocr_extraction import extract_text
from utils import resolve_image_path, load_csv_mapping


# Configuration
UPLOAD_DIR = os.environ.get("UPLOAD_DIR", "uploads")
IMAGES_DIR = os.environ.get("IMAGES_DIR", "real_aadhar")
MODEL_PATH = os.environ.get("MODEL_PATH", "models/aadhar_resnet_model.pth")
CSV_PATH = os.environ.get("CSV_PATH", "data/extracted_aadhaar_numbers.csv")
os.makedirs(UPLOAD_DIR, exist_ok=True)


app = Flask(__name__)


# Load model once
model, device = load_model(MODEL_PATH)
# Optional CSV mapping
csv_df = load_csv_mapping(CSV_PATH)


@app.route("/", methods=["GET"])
def home():
return jsonify({"message": "Aadhaar Verification API is running!"})


@app.route('/predict', methods=['POST'])
def predict_route():
if 'file' not in request.files:
return jsonify({"error": "No file uploaded (expect field name 'file')"}), 400
f = request.files['file']
filename = secure_filename(f.filename)
path = os.path.join(UPLOAD_DIR, filename)
f.save(path)


# Read bytes
with open(path, 'rb') as fh:
image_bytes = fh.read()


try:
status = predict_aadhar(model, device, image_bytes)
ocr_text = extract_text(image_bytes)
return jsonify({
"filename": filename,
"Aadhaar_Status": status,
"Extracted_Text": ocr_text
})
except Exception as e:
return jsonify({"error": str(e)}), 500


@app.route('/get_image', methods=['GET'])
def get_image_route():
image_id = request.args.get('image_id', type=int)
if image_id is None:
return jsonify({"error": "image_id not provided"}), 400
img_path = resolve_image_path(IMAGES_DIR, image_id)
if not img_path:
app.run(host='0.0.0.0', port=5000)