# -*- coding: utf-8 -*-
"""model_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9arUK-dBigkJKftT2CfHhadOxHaabcf
"""

import torch
import torch.nn as nn
from torchvision import models
import io
from PIL import Image
import torchvision.transforms as T


# Inference transforms
inference_tf = T.Compose([
T.Resize((224, 224)),
T.ToTensor(),
T.Normalize([0.485, 0.456, 0.406],[0.229, 0.224, 0.225]),
])




def load_model(model_path: str):
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = models.resnet18(pretrained=False)
model.fc = nn.Linear(model.fc.in_features, 2)
state = torch.load(model_path, map_location=device)
model.load_state_dict(state)
model.to(device).eval()
return model, device




def predict_aadhar(model, device, image_bytes: bytes) -> str:
img = Image.open(io.BytesIO(image_bytes)).convert('RGB')
x = inference_tf(img).unsqueeze(0).to(device)
with torch.no_grad():
out = model(x)
pred = out.argmax(1).item()
return 'Real Aadhaar' if pred == 0 else 'Fake Aadhaar'