# -*- coding: utf-8 -*-
"""ocr_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-AVVMhZMhl9rIrDp10gRlORcR9_5rXI
"""

import io
import numpy as np
from PIL import Image
import easyocr


reader = easyocr.Reader(['en'], gpu=False)




def extract_text(image_bytes: bytes) -> str:
img = Image.open(io.BytesIO(image_bytes)).convert('RGB')
arr = np.array(img)
results = reader.readtext(arr)
return ' '.join([r[1] for r in results]) if results else ''