# -*- coding: utf-8 -*-
"""utiles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOYys7U4sUyjiOoHpUL4QUIVdT2OxxTZ
"""

import os
import pandas as pd




def resolve_image_path(images_dir: str, image_id: int):
for ext in ('.jpg', '.jpeg', '.png'):
p = os.path.join(images_dir, f"{image_id}{ext}")
if os.path.exists(p):
return p
return None




def load_csv_mapping(csv_path: str):
if not csv_path:
return None
if not os.path.exists(csv_path):
return None
try:
df = pd.read_csv(csv_path)
df.columns = [c.lower() for c in df.columns]
# Ensure numeric image_number if possible
if 'image_filename' in df.columns and 'image_number' not in df.columns:
nums = df['image_filename'].astype(str).str.extract(r"(\d+)", expand=False)
df['image_number'] = pd.to_numeric(nums, errors='coerce').astype('Int64')
return df
except Exception:
return None